plugins {
    id 'application'
}

group = 'local.jvision'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def tomcatVersion = '9.0.102'

dependencies {
    implementation "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}"
    implementation "org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}"
    implementation 'javax.servlet.jsp.jstl:javax.servlet.jsp.jstl-api:1.2.1'
    implementation('org.glassfish.web:javax.servlet.jsp.jstl:1.2.5') {
        exclude group: 'xalan'
    }
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

application {
    mainClass = 'local.jvision.DevServer'
}

tasks.named('run', JavaExec) {
    standardInput = System.in
    ['port', 'contextPath'].each { key ->
        def value = System.getProperty(key)
        if (value != null) {
            systemProperty key, value
        }
    }
}
